"use client";

import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { StepForm } from "@/components/ui/StepForm";
import { ImageUploadField } from "@/components/ui/ImageUploadField";
import { musicOptions, templateCatalog } from "@/data/templates";
import { formatTamilDate } from "@/lib/utils";
import type { InvitationFormData, PreWeddingEvent, TamilTemplateId } from "@/types";

const defaultEvent = (title: string): PreWeddingEvent => ({ title, date: "", time: "", venue: "" });
const eventTitles = ["மருதாணி நிகழ்வு", "இசை நிகழ்வு", "மஞ்சள் நிகழ்வு"];

const emptyForm: InvitationFormData = {
  templateId: "rose-gold-blush", brideName: "", groomName: "", weddingDate: "", weddingTime: "", venueName: "", venueAddress: "", mapLink: "", bridePhoto: "", groomPhoto: "", couplePhoto: "", slideshowPhotos: [], photoCaptions: [], musicTrack: musicOptions[0].url, showPreWedding: false, preWeddingEvents: eventTitles.map(defaultEvent), showDressCode: false, dressCode: "", showTransport: false, transportInfo: "", isPublished: true,
};

export function InvitationEditor({ initialData, mode }: { initialData?: Partial<InvitationFormData>; mode: "create" | "edit" }) {
  const params = useSearchParams();
  const router = useRouter();
  const templateFromQuery = params.get("template") as TamilTemplateId | null;
  const [step, setStep] = useState(1);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [form, setForm] = useState<InvitationFormData>({ ...emptyForm, ...initialData, templateId: initialData?.templateId || templateFromQuery || emptyForm.templateId, preWeddingEvents: initialData?.preWeddingEvents && initialData.preWeddingEvents.length ? initialData.preWeddingEvents : emptyForm.preWeddingEvents });

  const selectedTemplate = useMemo(() => templateCatalog.find((template) => template.id === form.templateId) || templateCatalog[4], [form.templateId]);
  function updateField<K extends keyof InvitationFormData>(key: K, value: InvitationFormData[K]) { setForm((prev) => ({ ...prev, [key]: value })); }

  async function saveInvitation() {
    setSaving(true); setMessage("");
    const res = await fetch(mode === "create" ? "/api/invitation/create" : "/api/invitation/update", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
    const data = await res.json(); setSaving(false);
    if (!res.ok) return setMessage(data.error || "சேமிக்க முடியவில்லை");
    router.push("/admin/dashboard");
  }

  return <div className="grid gap-8 xl:grid-cols-[1.1fr_0.9fr]">{/* unchanged structure; only labels fixed */}
    <div className="space-y-6">
      {step===1 && <StepForm step={1} totalSteps={6} title="Template Selection" description="உங்கள் அழைப்பிதழின் தோற்றத்தைத் தேர்வு செய்யுங்கள்."><div className="grid gap-4 md:grid-cols-2">{templateCatalog.map((template)=><button type="button" key={template.id} onClick={()=>updateField("templateId",template.id)} className={`rounded-[24px] border p-4 text-left ${form.templateId===template.id?"border-brand.rose bg-rose-50":"border-rose-100 bg-white"}`}><div className={`h-28 rounded-2xl bg-gradient-to-br ${template.preview}`} /><p className="mt-3 font-tamil text-2xl">{template.name}</p><p className="text-sm text-slate-600">{template.animation}</p></button>)}</div></StepForm>}
      {step===2 && <StepForm step={2} totalSteps={6} title="Couple Details" description="மணமக்கள் விவரங்கள் மற்றும் புகைப்படங்களைச் சேர்க்கவும்."><div className="grid gap-5 sm:grid-cols-2"><input value={form.brideName} onChange={(e)=>updateField("brideName",e.target.value)} placeholder="மணமகள் பெயர்" className="rounded-2xl border border-rose-100 px-4 py-3" /><input value={form.groomName} onChange={(e)=>updateField("groomName",e.target.value)} placeholder="மணமகன் பெயர்" className="rounded-2xl border border-rose-100 px-4 py-3" /><ImageUploadField label="மணமகள் புகைப்படம்" value={form.bridePhoto} onChange={(url)=>updateField("bridePhoto",url)} /><ImageUploadField label="மணமகன் புகைப்படம்" value={form.groomPhoto} onChange={(url)=>updateField("groomPhoto",url)} /><div className="sm:col-span-2"><ImageUploadField label="சேர்ந்த புகைப்படம்" value={form.couplePhoto} onChange={(url)=>updateField("couplePhoto",url)} /></div></div></StepForm>}
      {step===3 && <StepForm step={3} totalSteps={6} title="Wedding Details" description="திருமண நிகழ்வு தொடர்பான விவரங்களை நிரப்பவும்."><div className="grid gap-5 sm:grid-cols-2"><input value={form.weddingDate} onChange={(e)=>updateField("weddingDate",e.target.value)} type="date" className="rounded-2xl border border-rose-100 px-4 py-3" /><input value={form.weddingTime} onChange={(e)=>updateField("weddingTime",e.target.value)} type="time" className="rounded-2xl border border-rose-100 px-4 py-3" /><input value={form.venueName} onChange={(e)=>updateField("venueName",e.target.value)} placeholder="திருமண இடம் பெயர்" className="rounded-2xl border border-rose-100 px-4 py-3 sm:col-span-2" /><textarea value={form.venueAddress} onChange={(e)=>updateField("venueAddress",e.target.value)} placeholder="முழு முகவரி" className="min-h-28 rounded-2xl border border-rose-100 px-4 py-3 sm:col-span-2" /><input value={form.mapLink ?? ""} onChange={(e)=>updateField("mapLink",e.target.value)} placeholder="Google Maps link" className="rounded-2xl border border-rose-100 px-4 py-3 sm:col-span-2" /></div></StepForm>}
      {step===4 && <StepForm step={4} totalSteps={6} title="Optional Sections" description="கூடுதல் நிகழ்வுகள் மற்றும் வசதிகளை toggle செய்து நிரப்பவும்."><div className="space-y-6"><label className="flex items-center gap-3"><input checked={form.showPreWedding} type="checkbox" onChange={(e)=>updateField("showPreWedding",e.target.checked)} />Pre-wedding events</label>{form.showPreWedding && <div className="grid gap-5">{form.preWeddingEvents.map((event,index)=><div key={event.title} className="grid gap-3 rounded-2xl border border-rose-100 p-4 sm:grid-cols-3"><p className="font-medium text-slate-900 sm:col-span-3">{event.title}</p><input value={event.date} onChange={(e)=>{const next=[...form.preWeddingEvents]; next[index]={...next[index],date:e.target.value}; updateField("preWeddingEvents",next);}} type="date" className="rounded-2xl border border-rose-100 px-4 py-3" /><input value={event.time} onChange={(e)=>{const next=[...form.preWeddingEvents]; next[index]={...next[index],time:e.target.value}; updateField("preWeddingEvents",next);}} type="time" className="rounded-2xl border border-rose-100 px-4 py-3" /><input value={event.venue} onChange={(e)=>{const next=[...form.preWeddingEvents]; next[index]={...next[index],venue:e.target.value}; updateField("preWeddingEvents",next);}} placeholder="Venue" className="rounded-2xl border border-rose-100 px-4 py-3" /></div>)}</div>}<label className="flex items-center gap-3"><input checked={form.showDressCode} type="checkbox" onChange={(e)=>updateField("showDressCode",e.target.checked)} />Dress code</label>{form.showDressCode && <textarea value={form.dressCode ?? ""} onChange={(e)=>updateField("dressCode",e.target.value)} placeholder="உடை நெறிமுறை" className="min-h-24 w-full rounded-2xl border border-rose-100 px-4 py-3" />}<label className="flex items-center gap-3"><input checked={form.showTransport} type="checkbox" onChange={(e)=>updateField("showTransport",e.target.checked)} />Transportation & stay</label>{form.showTransport && <textarea value={form.transportInfo ?? ""} onChange={(e)=>updateField("transportInfo",e.target.value)} placeholder="வாகன வசதி மற்றும் தங்கும் இடம்" className="min-h-24 w-full rounded-2xl border border-rose-100 px-4 py-3" />}</div></StepForm>}
      {step===5 && <StepForm step={5} totalSteps={6} title="Photos & Music" description="Gallery மற்றும் background music தேர்வு செய்யுங்கள்."><div className="space-y-6"><ImageUploadField label="Slideshow photos (max 10)" multiple onChange={()=>undefined} onMultipleChange={(urls)=>updateField("slideshowPhotos",[...form.slideshowPhotos,...urls].slice(0,10))} /><div className="grid gap-3 sm:grid-cols-2">{musicOptions.map((option)=><button type="button" key={option.id} onClick={()=>updateField("musicTrack",option.url)} className={`rounded-2xl border px-4 py-4 text-left ${form.musicTrack===option.url?"border-brand.rose bg-rose-50":"border-rose-100"}`}><p className="font-medium text-slate-900">{option.label}</p><p className="text-sm text-slate-600">Tamil instrumental preset</p></button>)}</div>{form.slideshowPhotos.length ? <div className="grid grid-cols-3 gap-3">{form.slideshowPhotos.map((url)=><img key={url} src={url} alt="slideshow" className="h-24 w-full rounded-2xl object-cover" />)}</div> : null}</div></StepForm>}
      {step===6 && <StepForm step={6} totalSteps={6} title="Preview & Publish" description="பதிவு செய்வதற்கு முன் preview-ஐ சரிபார்க்கவும்."><div className="space-y-4"><label className="flex items-center gap-3"><input checked={form.isPublished} type="checkbox" onChange={(e)=>updateField("isPublished",e.target.checked)} />அழைப்பிதழை வெளியிடு</label>{message ? <p className="text-sm text-red-500">{message}</p> : null}<button onClick={saveInvitation} disabled={saving} className="rounded-full bg-brand.rose px-6 py-3 font-semibold text-white">{saving ? "சேமிக்கப்படுகிறது..." : mode === "create" ? "அழைப்பிதழை வெளியிடு" : "மாற்றங்களை சேமி"}</button></div></StepForm>}
      <div className="flex items-center justify-between"><button type="button" disabled={step===1} onClick={()=>setStep((s)=>s-1)} className="rounded-full border border-rose-200 px-5 py-2 text-brand.rose disabled:opacity-40">முந்தைய படி</button><button type="button" disabled={step===6} onClick={()=>setStep((s)=>s+1)} className="rounded-full bg-slate-900 px-5 py-2 text-white disabled:opacity-40">அடுத்த படி</button></div>
    </div>
    <aside className="space-y-6 rounded-[32px] border border-white/10 bg-[#17131d] p-6 text-white xl:sticky xl:top-24 xl:h-fit"><div className={`h-44 rounded-[26px] bg-gradient-to-br ${selectedTemplate.preview}`} /><div><p className="font-display text-lg text-brand.blush">Live Preview</p><h3 className="mt-2 font-tamil text-4xl">{form.brideName || "மணமகள்"} & {form.groomName || "மணமகன்"}</h3><p className="mt-3 text-white/70">{form.weddingDate ? formatTamilDate(form.weddingDate) : "திருமண தேதி"} | {form.weddingTime || "நேரம்"}</p><p className="mt-2 text-white/70">{form.venueName || "திருமண இடம்"}</p></div>{form.couplePhoto ? <img src={form.couplePhoto} alt="couple" className="h-64 w-full rounded-[26px] object-cover" /> : null}<div className="rounded-[26px] border border-white/10 bg-white/5 p-5 text-white/80"><p className="font-tamil text-2xl text-white">{selectedTemplate.name}</p><p className="mt-2 text-sm">{selectedTemplate.description}</p><p className="mt-4 text-sm text-brand.gold">Generated slug preview: /invitation/{(form.brideName || "bride") + "-" + (form.groomName || "groom")}</p></div></aside>
  </div>;
}
